/*!
 * jQuery Text Typer
 * 
 * @version : 1.1.0
 * @author : Pathik Gandhi (http://pathikgandhi.info)
 * @plugin_uri : https://github.com/gr8pathik/canvas-bouncingballs
 * @plugin_demo : http://labs.pathikgandhi.info/canvas/bouncingballs/
 */

function degree(e){return e*(Math.PI/180)}function addCircle(e,t,n){if(typeof e=="undefined"){e=getRandomInt(1,canvas.width)}if(typeof t=="undefined"){t=getRandomInt(1,canvas.height)}if(typeof n=="undefined"){n=radiusWidth*Math.random()}if(e<n){e=n}else if(e>canvas.width-n){e=canvas.width-n}if(t<n){t=n}else if(t>canvas.height-n){t=canvas.height-n}circle.push({x:e,xvc:3*Math.random(),y:t,yvc:3*Math.random(),radius:n,color:"rgba("+(Math.random()*238).toFixed(0)+", "+(Math.random()*238).toFixed(0)+", "+(Math.random()*238).toFixed(0)+", 1.0)"});totalCircle()}function animateCircle(){context.clearRect(0,0,canvas.width,canvas.height);circle.forEach(function(e){context.beginPath();context.arc(e.x,e.y,e.radius,degree(0),degree(360),false);context.fillStyle=e.color;context.closePath();context.fill();changePosition(e)})}function changePosition(e){if(e.x+e.xvc+e.radius>canvas.width||e.x+e.xvc-e.radius<0){e.xvc=-e.xvc}if(e.y+e.yvc+e.radius>canvas.height||e.y+e.yvc-e.radius<0){e.yvc=-e.yvc}e.x+=e.xvc;e.y+=e.yvc}function totalCircle(){if(totalCircleBtn)totalCircleBtn.innerText=circle.length}function aminStatusChange(){if(aminStatusBtn)aminStatusBtn.innerText=pause==false?"Stopped":"Running"}function getRandomInt(e,t){return Math.floor(Math.random()*(t-e+1))+e}var canvas=document.getElementById("myCanvas");var pause=true;var circle=[];var isCanvasSupported=false;var context="";if(canvas.getContext){isCanvasSupported=true;context=canvas.getContext("2d")}var addCircleBtn=document.getElementById("addCircle");var startBtn=document.getElementById("startAnim");var stopBtn=document.getElementById("stopAnim");var totalCircleBtn=document.getElementById("totalCircles");var aminStatusBtn=document.getElementById("aminStatus");var resetAnimBtn=document.getElementById("resetAnim");var radiusWidth=50;var interTime=50;var defaultOption={};defaultOption.x=100;defaultOption.y=100;if(isCanvasSupported){addCircle();setInterval(function(){if(pause){animateCircle()}},interTime);canvas.addEventListener("click",function(e){console.log(e);var t;var n;var r=radiusWidth*Math.random();if(e.offsetX||e.offsetY){t=e.offsetX;n=e.offsetY}else{t=e.clientX+document.body.scrollLeft+document.documentElement.scrollLeft;n=e.clientY+document.body.scrollTop+document.documentElement.scrollTop}t-=canvas.offsetLeft;n-=canvas.offsetTop;console.log(t,n);addCircle(t,n,r)},false);if(addCircleBtn){addCircleBtn.addEventListener("click",function(e){var t=radiusWidth*Math.random();addCircle(undefined,undefined,t)},false)}if(startBtn){startBtn.addEventListener("click",function(){pause=true;aminStatusChange()},false)}if(resetAnimBtn){resetAnimBtn.addEventListener("click",function(){circle=[];addCircle()})}if(stopBtn){stopBtn.addEventListener("click",function(){pause=false;aminStatusChange()},false)}aminStatusChange()}else{alert("Canvas is not supported in you browser.")}